name: fastapi-mysql

services:   
  db-mysql:  
    image: mysql 
    container_name: db-mysql   
    environment:  
      MYSQL_ROOT_PASSWORD: quevedo
      MYSQL_DATABASE: dispositivos_db
      MYSQL_USER: daniel
      MYSQL_PASSWORD: 1234
    ports:  
      - "3306:3306"

